all: BP.png modelosGraficos.jpeg peligro_predador.jpeg fuego.jpg antartic.jpeg tsimane.jpg treeOfLife-liviano.png reciprocidad.jpeg regalo.png dedo.png cerradura.png deforestacion.jpg pachacuteckoricancha.jpg sidewalk_bubblegum_1997_4.png moneda-euro-liviana.png galton-board.jpg Elo1980.jpg boole.png sum_product.png test_chagas.png lifeHistory.jpeg

BP.png:
	wget https://raw.githubusercontent.com/glandfried/images/master/logos/BP.png -O BP.png

deforestacion.jpg:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/deforestacion.jpg

modelosGraficos.jpeg:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/modelosGraficos.jpeg

peligro_predador.jpeg:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/peligro_predador.jpeg

fuego.jpg:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/fuego.jpg

antartic.jpeg:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/antartic.jpeg

tsimane.jpg:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/tsimane.jpg

treeOfLife-liviano.png:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/treeOfLife-liviano.png

reciprocidad.jpeg:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/reciprocidad.jpeg

regalo.png:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/regalo.png

dedo.png:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/dedo.png

cerradura.png:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/cerradura.png

pachacuteckoricancha.jpg:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/pachacuteckoricancha.jpg

inti.png:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/inti.png

sidewalk_bubblegum_1997_4.png:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/sidewalk_bubblegum_1997_1.png
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/sidewalk_bubblegum_1997_2.png
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/sidewalk_bubblegum_1997_4.png

moneda-euro-liviana.png:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/moneda-euro-liviana.png

galton-board.jpg:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/galton-board.jpg

Elo1980.jpg:
	wget https://raw.githubusercontent.com/glandfried/images/master/Elo1980.jpg

boole.png:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/boole.png

sum_product.png:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/sum_product.png

test_chagas.png:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/test_chagas.png

lifeHistory.jpeg:
	wget https://raw.githubusercontent.com/glandfried/images/master/lifeHistory.jpeg
